/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author nico
 */
public class Codigobarra extends javax.swing.JFrame {
    String nombre;
    String apellido;
    /**
     * Creates new form Codigobarra
     */
    public Codigobarra(String nombreR, String apellidoR) {
        nombre=nombreR;
        apellido=apellidoR;
        initComponents();
        load();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblcode = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Se genero tu codigo de barras");
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblcode, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblcode, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     * "/Escritorio/Programacion/Proyecto/Proyecto/"+nombre+"_"+apellido+".png"
     */
    
    private void load(){
        ImageIcon icon = new ImageIcon("src/codigos/"+nombre+"_"+apellido+".png");
        lblcode.setIcon(icon);

    }     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblcode;
    // End of variables declaration//GEN-END:variables
}
